"""Creator Central — per-format content generation skills.

Each "skill" turns one research pack into one platform-ready content format,
generated by whatever model CLI is available (see ``cli_registry``). Skills are
independent and individually regeneratable; the autonomous job runs them all.

Add a format by appending to ``SKILLS``.
"""
from __future__ import annotations

import json
import os
from typing import Any, Dict, List, Optional

import cli_registry

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CREATOR_PROFILE_PATH = os.environ.get(
    "CREATOR_PROFILE_PATH", os.path.join(BASE_DIR, "config", "creator_profile.json")
)


def load_profile() -> Dict[str, Any]:
    try:
        with open(CREATOR_PROFILE_PATH, encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {}


def _voice(profile: Dict[str, Any]) -> str:
    banned = ", ".join(profile.get("banned_phrases", [])) or "(none)"
    return (
        f"You are the production team for {profile.get('channel_name', 'an AI creator channel')}.\n"
        f"Audience: {profile.get('audience', 'technical builders')}\n"
        f"Tone: {profile.get('tone', 'concrete, technical, no hype')}\n"
        f"Banned phrases (never use): {banned}.\n"
        "Be specific and technical. Use real numbers and names from the research. "
        "No preamble, no meta commentary — return only the asset."
    )


# --------------------------------------------------------------------------- #
# Format skills
# --------------------------------------------------------------------------- #
def _prompt_shorts(research: str, profile: Dict[str, Any]) -> str:
    lo = profile.get("format_rules", {}).get("short_script_min_seconds", 25)
    hi = profile.get("format_rules", {}).get("short_script_max_seconds", 60)
    return (
        f"Write a {lo}-{hi} second YouTube Short / Reel script from the research below.\n"
        "Structure: a 3-second cold hook, one sharp insight, one concrete proof point, "
        "one punchy close that drives a follow. Plain spoken sentences. Add [Visual] and "
        "[Audio] cues every couple of lines. Keep it under ~150 spoken words.\n\n"
        f"RESEARCH:\n{research[:6000]}"
    )


def _prompt_video(research: str, profile: Dict[str, Any]) -> str:
    return (
        "Write a full long-form YouTube video script from the research below.\n"
        "Sections, each labelled:\n"
        "  COLD OPEN — a 2-3 sentence hook that states the stakes.\n"
        "  BEAT 1 / BEAT 2 / BEAT 3 — the story, each beat with a spoken paragraph "
        "and a [B-ROLL] note.\n"
        "  DEMO — a concrete walkthrough the viewer could reproduce, with on-screen steps.\n"
        "  OUTRO — the takeaway + one clear call to action.\n"
        "Target 900-1300 words of spoken copy. Conversational but technically precise.\n\n"
        f"RESEARCH:\n{research[:6000]}"
    )


def _prompt_podcast(research: str, profile: Dict[str, Any]) -> str:
    return (
        "Write a ~5 minute two-host podcast script from the research below.\n"
        "Format as 'HOST A:' / 'HOST B:' alternating lines. Natural chemistry, real "
        "disagreement and clarification, no filler. Host A frames the news; Host B "
        "pushes on what it actually means for builders. End on a concrete 'try this'.\n\n"
        f"RESEARCH:\n{research[:6000]}"
    )


def _prompt_blog(research: str, profile: Dict[str, Any]) -> str:
    return (
        "Write a complete, publishable blog post (not an outline) from the research below.\n"
        "Markdown. Include: an H1 title, a 2-3 sentence intro that states why it matters, "
        "'## What it actually does' explaining the mechanism, '## Why it matters' for the "
        "audience, a fenced code block or copy-paste command if relevant, and a closing "
        "'## The takeaway'. 600-900 words. Technical, specific, no hype.\n\n"
        f"RESEARCH:\n{research[:6000]}"
    )


SKILLS: Dict[str, Dict[str, Any]] = {
    "shorts": {"label": "YouTube Short", "icon": "📱", "prompt": _prompt_shorts, "eta_sec": 30},
    "video":  {"label": "Long-form Video", "icon": "🎬", "prompt": _prompt_video, "eta_sec": 90},
    "podcast": {"label": "Podcast Script", "icon": "🎙️", "prompt": _prompt_podcast, "eta_sec": 90},
    "blog":   {"label": "Blog Post", "icon": "📝", "prompt": _prompt_blog, "eta_sec": 60},
}

FORMAT_ORDER: List[str] = ["shorts", "video", "podcast", "blog"]


def generate_format(fmt: str, research: str, profile: Optional[Dict[str, Any]] = None,
                    prefer: Optional[str] = None) -> Dict[str, Any]:
    """Run one format skill. Returns {format, label, body, provider, model, elapsed_ms, ok, error}."""
    skill = SKILLS.get(fmt)
    if not skill:
        return {"format": fmt, "ok": False, "error": "unknown_format"}
    profile = profile if profile is not None else load_profile()
    system = _voice(profile)
    prompt = skill["prompt"](research or "", profile)
    res = cli_registry.generate(prompt, system, prefer=prefer)
    return {
        "format": fmt,
        "label": skill["label"],
        "icon": skill["icon"],
        "body": res["text"] or "",
        "provider": res["provider"],
        "model": res["model"],
        "elapsed_ms": res["elapsed_ms"],
        "ok": bool(res["text"]),
        "error": None if res["text"] else "generation_failed",
    }


def generate_all(research: str, profile: Optional[Dict[str, Any]] = None,
                 formats: Optional[List[str]] = None,
                 on_format: Optional[Any] = None) -> List[Dict[str, Any]]:
    """Run every (or selected) format skill. `on_format(fmt, result)` called per completion."""
    profile = profile if profile is not None else load_profile()
    out = []
    for fmt in (formats or FORMAT_ORDER):
        result = generate_format(fmt, research, profile)
        out.append(result)
        if on_format:
            try:
                on_format(fmt, result)
            except Exception:
                pass
    return out


if __name__ == "__main__":
    import sys
    research = sys.argv[1] if len(sys.argv) > 1 else (
        "Llamafile 0.9 ships a single-binary local LLM runner. Runs a 3B model at "
        "~6 tok/s on a Raspberry Pi 4, no CUDA, 4-minute setup. Memory pressure climbs "
        "past 3.7GB once context fills."
    )
    fmt = sys.argv[2] if len(sys.argv) > 2 else "shorts"
    r = generate_format(fmt, research)
    print(f"[{r['format']}] via {r['provider']} in {r['elapsed_ms']}ms ok={r['ok']}\n")
    print(r["body"])
